.TH "_Evas_Engine_Info" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Evas_Engine_Info \- 
.PP
Generic engine information.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmagic\fP"
.br
.RI "\fIMagic number. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Generic engine information. 

Generic info is useless 

.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
