.TH "_Evas_Cserve_Image_Cache" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Evas_Cserve_Image_Cache \- 
.PP
Cache of images shared by server.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Cache of images shared by server. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
