.TH "_Evas_Event_Mouse_Up" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Evas_Event_Mouse_Up \- 
.PP
Mouse button release event.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBbutton\fP"
.br
.RI "\fIMouse button number that was raised (1 - 32). \fP"
.in -1c
.SH "Detailed Description"
.PP 
Mouse button release event. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
