.TH "_Evas_Event_Mouse_Out" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Evas_Event_Mouse_Out \- 
.PP
Mouse leave event.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBbuttons\fP"
.br
.RI "\fIButton pressed mask, Bits set to 1 are buttons currently pressed (bit 0 = mouse button 1, bit 1 = mouse button 2 etc. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Mouse leave event. 
.SH "Field Documentation"
.PP 
.SS "int \fB_Evas_Event_Mouse_Out::buttons\fP"
.PP
Button pressed mask, Bits set to 1 are buttons currently pressed (bit 0 = mouse button 1, bit 1 = mouse button 2 etc. ) 
.PP
Referenced by evas_event_feed_mouse_move(), evas_event_feed_mouse_out(), evas_event_feed_mouse_up(), and evas_object_hide().

.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
