.TH "_Evas_Cserve_Stats" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Evas_Cserve_Stats \- 
.PP
Statistics about server that shares cached bitmaps.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsaved_memory\fP"
.br
.RI "\fIcurrent saved memory, in bytes \fP"
.ti -1c
.RI "int \fBwasted_memory\fP"
.br
.RI "\fIcurrent wasted memory, in bytes \fP"
.ti -1c
.RI "int \fBsaved_memory_peak\fP"
.br
.RI "\fIpeak of saved memory, in bytes \fP"
.ti -1c
.RI "int \fBwasted_memory_peak\fP"
.br
.RI "\fIpeak of wasted memory, in bytes \fP"
.ti -1c
.RI "double \fBsaved_time_image_header_load\fP"
.br
.RI "\fItime, in seconds, saved in header loads by sharing cached loads instead \fP"
.ti -1c
.RI "double \fBsaved_time_image_data_load\fP"
.br
.RI "\fItime, in seconds, saved in data loads by sharing cached loads instead \fP"
.in -1c
.SH "Detailed Description"
.PP 
Statistics about server that shares cached bitmaps. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
