.TH "_Evas_Coord_Rectangle" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Evas_Coord_Rectangle \- 
.PP
< A rectangle in Evas_Coord  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "Evas_Coord \fBx\fP"
.br
.RI "\fItop-left x co-ordinate of rectangle \fP"
.ti -1c
.RI "Evas_Coord \fBy\fP"
.br
.RI "\fItop-left y co-ordinate of rectangle \fP"
.ti -1c
.RI "Evas_Coord \fBw\fP"
.br
.RI "\fIwidth of rectangle \fP"
.ti -1c
.RI "Evas_Coord \fBh\fP"
.br
.RI "\fIheight of rectangle \fP"
.in -1c
.SH "Detailed Description"
.PP 
< A rectangle in Evas_Coord 

.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
