.TH "_Evas_Cserve_Image" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Evas_Cserve_Image \- 
.PP
An image shared by the server.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
An image shared by the server. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
