.TH "_Evas_Event_Hold" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Evas_Event_Hold \- 
.PP
Hold change event.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBhold\fP"
.br
.RI "\fIThe hold flag. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Hold change event. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
