.TH "_Evas_Object_Box_Api" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Evas_Object_Box_Api \- 
.PP
This structure should be used by any class that wants to inherit from box to provide custom behavior not allowed only by providing a layout function with \fBevas_object_box_layout_set()\fP.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This structure should be used by any class that wants to inherit from box to provide custom behavior not allowed only by providing a layout function with \fBevas_object_box_layout_set()\fP. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
