.TH "_Evas_Object_Box_Data" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Evas_Object_Box_Data \- 
.PP
This structure augments clipped smart object's instance data, providing extra members required by generic box implementation.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This structure augments clipped smart object's instance data, providing extra members required by generic box implementation. 

If a subclass inherits from \fBEvas_Object_Box_Api\fP then it may augment \fBEvas_Object_Box_Data\fP to fit its own needs. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
