.TH "_Evas_Cserve_Config" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Evas_Cserve_Config \- 
.PP
Configuration that controls the server that shares cached bitmaps.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Configuration that controls the server that shares cached bitmaps. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
