.TH "_Evas_Event_Multi_Up" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Evas_Event_Multi_Up \- 
.PP
Multi button release event.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdevice\fP"
.br
.RI "\fIMulti device number that went up (1 or more for extra touches). \fP"
.in -1c
.SH "Detailed Description"
.PP 
Multi button release event. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
