.TH "Object Method Interceptors" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Object Method Interceptors \- 
.PP
Evas provides a way to intercept method calls.  

.SS "Functions"

.in +1c
.ti -1c
.RI "EAPI void \fBevas_object_intercept_show_callback_add\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Show_Cb func, const void *data)"
.br
.RI "\fISet the callback function that intercepts a show event of a object. \fP"
.ti -1c
.RI "EAPI void * \fBevas_object_intercept_show_callback_del\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Show_Cb func)"
.br
.RI "\fIUnset the callback function that intercepts a show event of a object. \fP"
.ti -1c
.RI "EAPI void \fBevas_object_intercept_hide_callback_add\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Hide_Cb func, const void *data)"
.br
.RI "\fISet the callback function that intercepts a hide event of a object. \fP"
.ti -1c
.RI "EAPI void * \fBevas_object_intercept_hide_callback_del\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Hide_Cb func)"
.br
.RI "\fIUnset the callback function that intercepts a hide event of a object. \fP"
.ti -1c
.RI "EAPI void \fBevas_object_intercept_move_callback_add\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Move_Cb func, const void *data)"
.br
.RI "\fISet the callback function that intercepts a move event of a object. \fP"
.ti -1c
.RI "EAPI void * \fBevas_object_intercept_move_callback_del\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Move_Cb func)"
.br
.RI "\fIUnset the callback function that intercepts a move event of a object. \fP"
.ti -1c
.RI "EAPI void \fBevas_object_intercept_resize_callback_add\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Resize_Cb func, const void *data)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void * \fBevas_object_intercept_resize_callback_del\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Resize_Cb func)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void \fBevas_object_intercept_raise_callback_add\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Raise_Cb func, const void *data)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void * \fBevas_object_intercept_raise_callback_del\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Raise_Cb func)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void \fBevas_object_intercept_lower_callback_add\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Lower_Cb func, const void *data)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void * \fBevas_object_intercept_lower_callback_del\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Lower_Cb func)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void \fBevas_object_intercept_stack_above_callback_add\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Stack_Above_Cb func, const void *data)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void * \fBevas_object_intercept_stack_above_callback_del\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Stack_Above_Cb func)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void \fBevas_object_intercept_stack_below_callback_add\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Stack_Below_Cb func, const void *data)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void * \fBevas_object_intercept_stack_below_callback_del\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Stack_Below_Cb func)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void \fBevas_object_intercept_layer_set_callback_add\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Layer_Set_Cb func, const void *data)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void * \fBevas_object_intercept_layer_set_callback_del\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Layer_Set_Cb func)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void \fBevas_object_intercept_color_set_callback_add\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Color_Set_Cb func, const void *data)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void * \fBevas_object_intercept_color_set_callback_del\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Color_Set_Cb func)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void \fBevas_object_intercept_clip_set_callback_add\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Clip_Set_Cb func, const void *data)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void * \fBevas_object_intercept_clip_set_callback_del\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Clip_Set_Cb func)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void \fBevas_object_intercept_clip_unset_callback_add\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Clip_Unset_Cb func, const void *data)"
.br
.RI "\fITo be documented. \fP"
.ti -1c
.RI "EAPI void * \fBevas_object_intercept_clip_unset_callback_del\fP (\fBEvas_Object\fP *obj, Evas_Object_Intercept_Clip_Unset_Cb func)"
.br
.RI "\fITo be documented. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Evas provides a way to intercept method calls. 

The interceptor callback may opt to completely deny the call, or may check and change the parameters before continuing. The continuation of an intercepted call is done by calling the intercepted call again, from inside the interceptor callback. 
.SH "Function Documentation"
.PP 
.SS "EAPI void evas_object_intercept_clip_set_callback_add (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Clip_Set_Cb func, const void * data)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void* evas_object_intercept_clip_set_callback_del (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Clip_Set_Cb func)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void evas_object_intercept_clip_unset_callback_add (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Clip_Unset_Cb func, const void * data)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void* evas_object_intercept_clip_unset_callback_del (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Clip_Unset_Cb func)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void evas_object_intercept_color_set_callback_add (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Color_Set_Cb func, const void * data)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void* evas_object_intercept_color_set_callback_del (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Color_Set_Cb func)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void evas_object_intercept_hide_callback_add (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Hide_Cb func, const void * data)"
.PP
Set the callback function that intercepts a hide event of a object. \fBParameters:\fP
.RS 4
\fIobj\fP The given canvas object pointer. 
.br
\fIfunc\fP The given function to be the callback function. 
.br
\fIdata\fP The data passed to the callback function.
.RE
.PP
This function sets a callback function to intercepts a hide event of a canvas object.
.PP
\fBSee also:\fP
.RS 4
\fBevas_object_intercept_hide_callback_del()\fP. 
.RE
.PP

.SS "EAPI void* evas_object_intercept_hide_callback_del (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Hide_Cb func)"
.PP
Unset the callback function that intercepts a hide event of a object. \fBParameters:\fP
.RS 4
\fIobj\fP The given canvas object pointer. 
.br
\fIfunc\fP The given callback function.
.RE
.PP
This function sets a callback function to intercepts a hide event of a canvas object.
.PP
\fBSee also:\fP
.RS 4
\fBevas_object_intercept_hide_callback_add()\fP. 
.RE
.PP

.SS "EAPI void evas_object_intercept_layer_set_callback_add (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Layer_Set_Cb func, const void * data)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void* evas_object_intercept_layer_set_callback_del (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Layer_Set_Cb func)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void evas_object_intercept_lower_callback_add (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Lower_Cb func, const void * data)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void* evas_object_intercept_lower_callback_del (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Lower_Cb func)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void evas_object_intercept_move_callback_add (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Move_Cb func, const void * data)"
.PP
Set the callback function that intercepts a move event of a object. \fBParameters:\fP
.RS 4
\fIobj\fP The given canvas object pointer. 
.br
\fIfunc\fP The given function to be the callback function. 
.br
\fIdata\fP The data passed to the callback function.
.RE
.PP
This function sets a callback function to intercepts a move event of a canvas object.
.PP
\fBSee also:\fP
.RS 4
\fBevas_object_intercept_move_callback_del()\fP. 
.RE
.PP

.SS "EAPI void* evas_object_intercept_move_callback_del (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Move_Cb func)"
.PP
Unset the callback function that intercepts a move event of a object. \fBParameters:\fP
.RS 4
\fIobj\fP The given canvas object pointer. 
.br
\fIfunc\fP The given callback function.
.RE
.PP
This function sets a callback function to intercepts a move event of a canvas object.
.PP
\fBSee also:\fP
.RS 4
\fBevas_object_intercept_move_callback_add()\fP. 
.RE
.PP

.SS "EAPI void evas_object_intercept_raise_callback_add (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Raise_Cb func, const void * data)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void* evas_object_intercept_raise_callback_del (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Raise_Cb func)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void evas_object_intercept_resize_callback_add (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Resize_Cb func, const void * data)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void* evas_object_intercept_resize_callback_del (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Resize_Cb func)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void evas_object_intercept_show_callback_add (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Show_Cb func, const void * data)"
.PP
Set the callback function that intercepts a show event of a object. \fBParameters:\fP
.RS 4
\fIobj\fP The given canvas object pointer. 
.br
\fIfunc\fP The given function to be the callback function. 
.br
\fIdata\fP The data passed to the callback function.
.RE
.PP
This function sets a callback function to intercepts a show event of a canvas object.
.PP
\fBSee also:\fP
.RS 4
\fBevas_object_intercept_show_callback_del()\fP. 
.RE
.PP

.SS "EAPI void* evas_object_intercept_show_callback_del (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Show_Cb func)"
.PP
Unset the callback function that intercepts a show event of a object. \fBParameters:\fP
.RS 4
\fIobj\fP The given canvas object pointer. 
.br
\fIfunc\fP The given callback function.
.RE
.PP
This function sets a callback function to intercepts a show event of a canvas object.
.PP
\fBSee also:\fP
.RS 4
\fBevas_object_intercept_show_callback_add()\fP. 
.RE
.PP

.SS "EAPI void evas_object_intercept_stack_above_callback_add (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Stack_Above_Cb func, const void * data)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void* evas_object_intercept_stack_above_callback_del (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Stack_Above_Cb func)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void evas_object_intercept_stack_below_callback_add (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Stack_Below_Cb func, const void * data)"
.PP
To be documented. FIXME: To be fixed. 
.SS "EAPI void* evas_object_intercept_stack_below_callback_del (\fBEvas_Object\fP * obj, Evas_Object_Intercept_Stack_Below_Cb func)"
.PP
To be documented. FIXME: To be fixed. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
