.TH "Rectangle Object Functions" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rectangle Object Functions \- 
.PP
Functions that operate on evas rectangle objects.  

.SS "Functions"

.in +1c
.ti -1c
.RI "EAPI \fBEvas_Object\fP * \fBevas_object_rectangle_add\fP (\fBEvas\fP *e)"
.br
.RI "\fIAdds a rectangle to the given evas. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Functions that operate on evas rectangle objects. 
.SH "Function Documentation"
.PP 
.SS "EAPI \fBEvas_Object\fP* evas_object_rectangle_add (\fBEvas\fP * e)"
.PP
Adds a rectangle to the given evas. \fBParameters:\fP
.RS 4
\fIe\fP The given evas. 
.RE
.PP
\fBReturns:\fP
.RS 4
The new rectangle object. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
