.TH "Specific Object Functions" 3 "Tue Apr 19 2011" "Evas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Specific Object Functions \- 
.PP
Functions that work on specific objects.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBRectangle Object Functions\fP"
.br
.PP

.RI "\fIFunctions that operate on evas rectangle objects. \fP"
.ti -1c
.RI "\fBImage Object Functions\fP"
.br
.PP

.RI "\fIFunctions used to create and manipulate image objects. \fP"
.ti -1c
.RI "\fBText Object Functions\fP"
.br
.PP

.RI "\fIFunctions that operate on single line, single style text objects. \fP"
.ti -1c
.RI "\fBTextblock Object Functions\fP"
.br
.PP

.RI "\fIFunctions used to create and manipulate textblock objects. \fP"
.ti -1c
.RI "\fBLine Object Functions\fP"
.br
.PP

.RI "\fIFunctions used to deal with evas line objects. \fP"
.ti -1c
.RI "\fBPolygon Object Functions\fP"
.br
.PP

.RI "\fIFunctions that operate on evas polygon objects. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Functions that work on specific objects. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Evas from the source code.
