"#ifdef GL_ES\n"
"#ifdef GL_FRAGMENT_PRECISION_HIGH\n"
"precision highp float;\n"
"#else\n"
"precision mediump float;\n"
"#endif\n"
"#endif\n"
"uniform sampler2D tex;\n"
"uniform sampler2D texm;\n"
"varying vec4 col;\n"
"varying vec2 tex_c;\n"
"varying vec2 tex_m;\n"
"void main()\n"
"{\n"
"   gl_FragColor = texture2D(tex, tex_c.xy).aaaa * texture2D(texm, tex_m.xy).aaaa * col;\n"
"}\n"
"\n"
