"#ifdef GL_ES\n"
"precision highp float;\n"
"#endif\n"
"attribute vec4 vertex, color;\n"
"attribute vec2 tex_coord, tex_coordm, tex_sample;\n"
"uniform mat4 mvp;\n"
"varying vec2 tex_c, tex_m;\n"
"varying vec4 col;\n"
"void main()\n"
"{\n"
"   gl_Position = mvp * vertex;\n"
"   tex_c = tex_coord;\n"
"   col = color;\n"
"\n"
"   // tex_coorda contains the Y-invert flag\n"
"   // position on screen in [0..1] range of current pixel\n"
"   vec4 mask_Position = mvp * vertex * vec4(0.5, sign(tex_sample.y) * 0.5, 0.5, 0.5) + vec4(0.5, 0.5, 0, 0);\n"
"   tex_m = mask_Position.xy * abs(tex_sample) + tex_coordm;\n"
"}\n"
