"#extension GL_OES_EGL_image_external : require\n"
"\n"
"#ifdef GL_FRAGMENT_PRECISION_HIGH\n"
"precision highp float;\n"
"#else\n"
"precision mediump float;\n"
"#endif\n"
"uniform samplerExternalOES tex;\n"
"uniform sampler2D texm;\n"
"varying vec4 col;\n"
"varying vec2 coord_c;\n"
"varying vec2 coord_m;\n"
"void main()\n"
"{\n"
"   gl_FragColor = texture2D(tex, coord_c.xy) * texture2D(texm, coord_m.xy).a * col;\n"
"}\n"
