Evas: Canvas Functions
Enlightenment
Beauty at your fingertips
Docs
Tracker
Contact
Contribute
Support
Download
About
News
Home
Evas Documentation at Tue Apr 19 2011
Todo
Files
Data Structures
Globals
Modules
Related Pages
Main Page
Canvas Functions
Functions that deal with the basic evas object.
Modules
Render Engine Functions
Functions that are used to set the render engine for a given function, and then get that engine working.
Output and Viewport Resizing Functions
Functions that set and retrieve the output and viewport size of an evas.
Coordinate Mapping Functions
Functions that are used to map coordinates from the canvas to the screen or the screen to the canvas.
Pointer (Mouse) Functions
Functions that deal with the status of the pointer (mouse cursor).
Event Freezing Functions
Functions that deal with the freezing of event processing of an evas.
Event Feeding Functions
Functions to tell Evas that events happened and should be processed.
Canvas Events
Canvas generates some events.
Image Functions
Functions that deals with images at canvas level.
Font Functions
Functions that deals with fonts.
Typedefs
typedef struct _Evas Evas
An Evas canvas handle.
Functions
EAPI Evas * evas_new (void)
Creates a new empty evas.
EAPI void evas_free (Evas *e)
Frees the given evas and any objects created on it.
EAPI void evas_data_attach_set (Evas *e, void *data)
Attaches a specific pointer to the evas for fetching later.
EAPI void * evas_data_attach_get (const Evas *e)
Returns the pointer attached by evas_data_attach_set().
EAPI void evas_focus_in (Evas *e)
Inform to the evas that it got the focus.
EAPI void evas_focus_out (Evas *e)
Inform to the evas that it lost the focus.
EAPI Eina_Bool evas_focus_state_get (const Evas *e)
Get the focus state known by the given evas.
EAPI void evas_nochange_push (Evas *e)
Push the nochange flag up 1.
EAPI void evas_nochange_pop (Evas *e)
Pop the nochange flag down 1.
EAPI void evas_damage_rectangle_add (Evas *e, int x, int y, int w, int h)
Add a damage rectangle.
EAPI void evas_obscured_rectangle_add (Evas *e, int x, int y, int w, int h)
Add an obscured region.
EAPI void evas_obscured_clear (Evas *e)
Remove all obscured region rectangles from the canvas.
EAPI void evas_render_updates_free (Eina_List *updates)
Free the rectangles returned by evas_render_updates().
EAPI Eina_List * evas_render_updates (Evas *e)
Force immediate renderization of the given canvas.
EAPI void evas_render (Evas *e)
Force renderization of the given canvas.
EAPI void evas_norender (Evas *e)
Update the canvas internal objects but not triggering immediate renderization.
EAPI void evas_render_idle_flush (Evas *e)
Make the canvas discard internally cached data used for rendering.
Detailed Description
Functions that deal with the basic evas object.
They are the functions you need to use at a minimum to get a working evas, and to destroy it.
Typedef Documentation
Evas
An Evas canvas handle.
See also:
evas_new()
evas_free()
Function Documentation
EAPI void evas_damage_rectangle_add (Evas * e, int x, int y, int w, int h)
Add a damage rectangle.
Parameters:
e The given canvas pointer.
x The rectangle's left position.
y The rectangle's top position.
w The rectangle's width.
h The rectangle's height.
This is the function by which one tells evas that a part of the canvas has to be repainted.
Referenced by evas_object_clip_set(), and evas_object_clip_unset().
EAPI void* evas_data_attach_get (const Evas * e)
Returns the pointer attached by evas_data_attach_set().
Parameters:
e The canvas to attach the pointer to
Returns:
The pointer attached
EAPI void evas_data_attach_set (Evas * e, void * data)
Attaches a specific pointer to the evas for fetching later.
Parameters:
e The canvas to attach the pointer to
data The pointer to attach
EAPI void evas_focus_in (Evas * e)
Inform to the evas that it got the focus.
Parameters:
e The evas to change information.
References EVAS_CALLBACK_CANVAS_FOCUS_IN.
EAPI void evas_focus_out (Evas * e)
Inform to the evas that it lost the focus.
Parameters:
e The evas to change information.
References EVAS_CALLBACK_CANVAS_FOCUS_OUT.
EAPI Eina_Bool evas_focus_state_get (const Evas * e)
Get the focus state known by the given evas.
Parameters:
e The evas to query information.
EAPI void evas_free (Evas * e)
Frees the given evas and any objects created on it.
Any objects with 'free' callbacks will have those callbacks called in this function.
Parameters:
e The given evas.
References evas_font_path_clear(), and evas_render_idle_flush().
EAPI Evas* evas_new (void)
Creates a new empty evas.
Note that before you can use the evas, you will to at a minimum:
Set its render method with evas_output_method_set .
Set its viewport size with evas_output_viewport_set .
Set its size of the canvas with evas_output_size_set .
Ensure that the render engine is given the correct settings with evas_engine_info_set .
This function should only fail if the memory allocation fails
Note:
this function is very low level. Instead of using it directly, consider using the high level functions in Ecore_Evas such as ecore_evas_new(). See http://docs.enlightenment.org/auto/ecore/.
Attention:
it is recommended that one calls evas_init() before creating new canvas.
Returns:
A new uninitialised Evas canvas on success. Otherwise, NULL.
EAPI void evas_nochange_pop (Evas * e)
Pop the nochange flag down 1.
This tells evas, that while the nochange flag is greater than 0, do not mark objects as "changed" when making changes.
Parameters:
e The evas to change information.
EAPI void evas_nochange_push (Evas * e)
Push the nochange flag up 1.
This tells evas, that while the nochange flag is greater than 0, do not mark objects as "changed" when making changes.
Parameters:
e The evas to change information.
EAPI void evas_norender (Evas * e)
Update the canvas internal objects but not triggering immediate renderization.
Parameters:
e The given canvas pointer.
This function updates the canvas internal objects not triggering renderization. To force renderization function evas_render() should be used.
See also:
evas_render.
EAPI void evas_obscured_clear (Evas * e)
Remove all obscured region rectangles from the canvas.
Parameters:
e The given canvas pointer.
This function removes all the rectangles from the obscured list of the canvas. It takes obscured areas added with evas_obscured_rectangle_add() and makes it a region that have to be repainted.
EAPI void evas_obscured_rectangle_add (Evas * e, int x, int y, int w, int h)
Add an obscured region.
Parameters:
e The given canvas pointer.
x The rectangle's left position.
y The rectangle's top position
w The rectangle's width.
h The rectangle's height.
This is the function by which one tells evas that a part of the canvas has not to be repainted. To make this region one that have to be repainted, call the function evas_obscured_clear().
See also:
evas_obscured_clear().
EAPI void evas_render (Evas * e)
Force renderization of the given canvas.
Parameters:
e The given canvas pointer.
EAPI void evas_render_idle_flush (Evas * e)
Make the canvas discard internally cached data used for rendering.
Parameters:
e The given canvas pointer.
This function flushes the arrays of delete, active and render objects. Other things it may also discard are: shared memory segments, temporary scratch buffers, cached data to avoid re-compute of that data etc.
Referenced by evas_free().
EAPI Eina_List* evas_render_updates (Evas * e)
Force immediate renderization of the given canvas.
Parameters:
e The given canvas pointer.
Returns:
A newly allocated list of updated rectangles of the canvas. Free this list with evas_render_updates_free().
This function forces an immediate renderization update of the given given canvas.
EAPI void evas_render_updates_free (Eina_List * updates)
Free the rectangles returned by evas_render_updates().
Parameters:
updates The list of updated rectangles of the canvas.
This function removes the region from the render updates list. It makes the region doesn't be render updated anymore.
Copyright ©2011 Enlightenment Docs generated Tue Apr 19 2011 18:18:31