Evas: Size Hints
Enlightenment
Beauty at your fingertips
Docs
Tracker
Contact
Contribute
Support
Download
About
News
Home
Evas Documentation at Tue Apr 19 2011
Todo
Files
Data Structures
Globals
Modules
Related Pages
Main Page
Size Hints
[Generic Object Functions]
Objects may carry hints so another object that acts as a manager (see Smart Object Functions) may know how to properly position and resize the object.
Functions
EAPI void evas_object_size_hint_min_get (const Evas_Object *obj, Evas_Coord *w, Evas_Coord *h)
Retrieves the size hint for the minimum size.
EAPI void evas_object_size_hint_min_set (Evas_Object *obj, Evas_Coord w, Evas_Coord h)
Sets the size hint for the minimum size.
EAPI void evas_object_size_hint_max_get (const Evas_Object *obj, Evas_Coord *w, Evas_Coord *h)
Retrieves the size hint for the maximum size.
EAPI void evas_object_size_hint_max_set (Evas_Object *obj, Evas_Coord w, Evas_Coord h)
Sets the size hint for the maximum size.
EAPI void evas_object_size_hint_request_get (const Evas_Object *obj, Evas_Coord *w, Evas_Coord *h)
Retrieves the size request hint.
EAPI void evas_object_size_hint_request_set (Evas_Object *obj, Evas_Coord w, Evas_Coord h)
Sets the requested size hint.
EAPI void evas_object_size_hint_aspect_get (const Evas_Object *obj, Evas_Aspect_Control *aspect, Evas_Coord *w, Evas_Coord *h)
Retrieves the size aspect control hint.
EAPI void evas_object_size_hint_aspect_set (Evas_Object *obj, Evas_Aspect_Control aspect, Evas_Coord w, Evas_Coord h)
Sets the size aspect control hint.
EAPI void evas_object_size_hint_align_get (const Evas_Object *obj, double *x, double *y)
Retrieves the size align control hint.
EAPI void evas_object_size_hint_align_set (Evas_Object *obj, double x, double y)
Sets the size align control hint.
EAPI void evas_object_size_hint_weight_get (const Evas_Object *obj, double *x, double *y)
Retrieves the size weight control hint.
EAPI void evas_object_size_hint_weight_set (Evas_Object *obj, double x, double y)
Sets the size weight control hint.
EAPI void evas_object_size_hint_padding_get (const Evas_Object *obj, Evas_Coord *l, Evas_Coord *r, Evas_Coord *t, Evas_Coord *b)
Retrieves the size padding control hint.
EAPI void evas_object_size_hint_padding_set (Evas_Object *obj, Evas_Coord l, Evas_Coord r, Evas_Coord t, Evas_Coord b)
Sets the size padding control hint.
Detailed Description
Objects may carry hints so another object that acts as a manager (see Smart Object Functions) may know how to properly position and resize the object.
The Size Hints provide a common interface that is recommended as the protocol for such information.
Function Documentation
EAPI void evas_object_size_hint_align_get (const Evas_Object * obj, double * x, double * y)
Retrieves the size align control hint.
This is not a size enforcement in any way, it's just a hint that should be used whenever appropriate.
Note that if any of x or y are NULL, the NULL parameters are ignored.
Parameters:
obj The given evas object.
x Pointer to a double in which to store the align x.
y Pointer to a double in which to store the align y.
Referenced by evas_object_box_layout_flow_horizontal(), evas_object_box_layout_flow_vertical(), evas_object_box_layout_homogeneous_horizontal(), evas_object_box_layout_homogeneous_max_size_horizontal(), evas_object_box_layout_homogeneous_max_size_vertical(), evas_object_box_layout_homogeneous_vertical(), evas_object_box_layout_horizontal(), evas_object_box_layout_stack(), and evas_object_box_layout_vertical().
EAPI void evas_object_size_hint_align_set (Evas_Object * obj, double x, double y)
Sets the size align control hint.
This is not a size enforcement in any way, it's just a hint that should be used whenever appropriate.
Accepted values are in the 0.0 to 1.0 range, with the special value -1.0 used to specify "justify" or "fill" by some users. See documentation of possible users.
Parameters:
obj The given evas object.
x Double (0.0..1.0 or -1.0) to use as align x hint.
y Double (0.0..1.0 or -1.0) to use as align y hint.
EAPI void evas_object_size_hint_aspect_get (const Evas_Object * obj, Evas_Aspect_Control * aspect, Evas_Coord * w, Evas_Coord * h)
Retrieves the size aspect control hint.
This is not a size enforcement in any way, it's just a hint that should be used whenever appropriate.
Note that if any of aspect, w or h are NULL, the NULL parameters are ignored.
Parameters:
obj The given evas object.
aspect Returns the hint on how size should be calculated.
w Pointer to an integer in which to store the aspect width.
h Pointer to an integer in which to store the aspect height.
EAPI void evas_object_size_hint_aspect_set (Evas_Object * obj, Evas_Aspect_Control aspect, Evas_Coord w, Evas_Coord h)
Sets the size aspect control hint.
This is not a size enforcement in any way, it's just a hint that should be used whenever appropriate.
Parameters:
obj The given evas object.
aspect Hint on how to calculate size.
w Integer to use as aspect width hint.
h Integer to use as aspect height hint.
EAPI void evas_object_size_hint_max_get (const Evas_Object * obj, Evas_Coord * w, Evas_Coord * h)
Retrieves the size hint for the maximum size.
This is not a size enforcement in any way, it's just a hint that should be used whenever appropriate.
Note that if any of w or h are NULL, the NULL parameters are ignored.
Parameters:
obj The given evas object.
w Pointer to an integer in which to store the maximum width.
h Pointer to an integer in which to store the maximum height.
Referenced by evas_object_box_layout_homogeneous_horizontal(), evas_object_box_layout_homogeneous_max_size_horizontal(), evas_object_box_layout_homogeneous_max_size_vertical(), evas_object_box_layout_homogeneous_vertical(), evas_object_box_layout_horizontal(), evas_object_box_layout_stack(), and evas_object_box_layout_vertical().
EAPI void evas_object_size_hint_max_set (Evas_Object * obj, Evas_Coord w, Evas_Coord h)
Sets the size hint for the maximum size.
This is not a size enforcement in any way, it's just a hint that should be used whenever appropriate.
Value -1 is considered unset.
Parameters:
obj The given evas object.
w Integer to use as the maximum width hint.
h Integer to use as the maximum height hint.
EAPI void evas_object_size_hint_min_get (const Evas_Object * obj, Evas_Coord * w, Evas_Coord * h)
Retrieves the size hint for the minimum size.
This is not a size enforcement in any way, it's just a hint that should be used whenever appropriate.
Note that if any of w or h are NULL, the NULL parameters are ignored.
Parameters:
obj The given evas object.
w Pointer to an integer in which to store the minimum width.
h Pointer to an integer in which to store the minimum height.
Referenced by evas_object_box_layout_homogeneous_horizontal(), evas_object_box_layout_homogeneous_max_size_horizontal(), evas_object_box_layout_homogeneous_max_size_vertical(), evas_object_box_layout_homogeneous_vertical(), and evas_object_box_layout_stack().
EAPI void evas_object_size_hint_min_set (Evas_Object * obj, Evas_Coord w, Evas_Coord h)
Sets the size hint for the minimum size.
This is not a size enforcement in any way, it's just a hint that should be used whenever appropriate.
Value 0 is considered unset.
Parameters:
obj The given evas object.
w Integer to use as the minimum width hint.
h Integer to use as the minimum height hint.
Referenced by evas_object_box_layout_flow_horizontal(), evas_object_box_layout_flow_vertical(), evas_object_box_layout_homogeneous_horizontal(), evas_object_box_layout_homogeneous_max_size_horizontal(), evas_object_box_layout_homogeneous_max_size_vertical(), evas_object_box_layout_homogeneous_vertical(), evas_object_box_layout_horizontal(), evas_object_box_layout_stack(), and evas_object_box_layout_vertical().
EAPI void evas_object_size_hint_padding_get (const Evas_Object * obj, Evas_Coord * l, Evas_Coord * r, Evas_Coord * t, Evas_Coord * b)
Retrieves the size padding control hint.
This is not a size enforcement in any way, it's just a hint that should be used whenever appropriate.
Note that if any of l, r, t or b are NULL, the NULL parameters are ignored.
Parameters:
obj The given evas object.
l Pointer to an integer in which to store left padding.
r Pointer to an integer in which to store right padding.
t Pointer to an integer in which to store top padding.
b Pointer to an integer in which to store bottom padding.
Referenced by evas_object_box_layout_flow_horizontal(), evas_object_box_layout_flow_vertical(), evas_object_box_layout_homogeneous_horizontal(), evas_object_box_layout_homogeneous_max_size_horizontal(), evas_object_box_layout_homogeneous_max_size_vertical(), evas_object_box_layout_homogeneous_vertical(), evas_object_box_layout_horizontal(), evas_object_box_layout_stack(), and evas_object_box_layout_vertical().
EAPI void evas_object_size_hint_padding_set (Evas_Object * obj, Evas_Coord l, Evas_Coord r, Evas_Coord t, Evas_Coord b)
Sets the size padding control hint.
This is not a size enforcement in any way, it's just a hint that should be used whenever appropriate.
Parameters:
obj The given evas object.
l Integer to specify left padding.
r Integer to specify right padding.
t Integer to specify top padding.
b Integer to specify bottom padding.
EAPI void evas_object_size_hint_request_get (const Evas_Object * obj, Evas_Coord * w, Evas_Coord * h)
Retrieves the size request hint.
This is not a size enforcement in any way, it's just a hint that should be used whenever appropriate.
Note that if any of w or h are NULL, the NULL parameters are ignored.
Parameters:
obj The given evas object.
w Pointer to an integer in which to store the requested width.
h Pointer to an integer in which to store the requested height.
EAPI void evas_object_size_hint_request_set (Evas_Object * obj, Evas_Coord w, Evas_Coord h)
Sets the requested size hint.
This is not a size enforcement in any way, it's just a hint that should be used whenever appropriate.
Value 0 is considered unset.
Parameters:
obj The given evas object.
w Integer to use as the preferred width hint.
h Integer to use as the preferred height hint.
EAPI void evas_object_size_hint_weight_get (const Evas_Object * obj, double * x, double * y)
Retrieves the size weight control hint.
This is not a size enforcement in any way, it's just a hint that should be used whenever appropriate.
Note that if any of x or y are NULL, the NULL parameters are ignored.
Accepted values are zero or positive values. Some users might use this hint as a boolean, but some might consider it as a proportion, see documentation of possible users.
Parameters:
obj The given evas object.
x Pointer to a double in which to store the weight x.
y Pointer to a double in which to store the weight y.
Referenced by evas_object_box_layout_horizontal(), and evas_object_box_layout_vertical().
EAPI void evas_object_size_hint_weight_set (Evas_Object * obj, double x, double y)
Sets the size weight control hint.
This is not a size enforcement in any way, it's just a hint that should be used whenever appropriate.
Parameters:
obj The given evas object.
x Double (0.0-1.0) to use as weight x hint.
y Double (0.0-1.0) to use as weight y hint.
Copyright ©2011 Enlightenment Docs generated Tue Apr 19 2011 18:18:31